version: '3.8'

# Credenciais AWS, SMTP e WhatsApp vêm do banco (tabela other_settings)
# Apenas variáveis essenciais são necessárias aqui

services:
  app:
    build: .
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - COMPANY_INIT=${COMPANY_INIT}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
      - CRON_SECRET=${CRON_SECRET}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/api/v1/maintenance-check"]
      interval: 30s
      timeout: 5s
      retries: 5

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=vinha
      - POSTGRES_PASSWORD=vinha123
      - POSTGRES_DB=vinha_admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vinha"]
      interval: 30s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
