# EasyPanel Configuration for Vinha Admin Center
name: vinha-admin-center
services:
  - type: app
    data:
      projectName: vinha-admin-center
      serviceName: app
      source:
        type: github
        repo: multideskio/vinha-admin-center
        branch: main
      build:
        type: dockerfile
        dockerfile: Dockerfile
      deploy:
        replicas: 1
        command: null
        zeroDowntime: true
      env:
        - key: NODE_ENV
          value: production
        - key: PORT
          value: '9002'
        - key: NEXT_TELEMETRY_DISABLED
          value: '1'
        # Adicione suas variáveis de ambiente aqui
        - key: DATABASE_URL
          value: ${DATABASE_URL}
        - key: JWT_SECRET
          value: ${JWT_SECRET}
        - key: COMPANY_INIT
          value: ${COMPANY_INIT}
        - key: NEXT_PUBLIC_APP_URL
          value: ${NEXT_PUBLIC_APP_URL}
      mounts: []
      ports:
        - published: 80
          target: 9002
      domains:
        - name: vinha-admin-center.seu-dominio.com
      healthcheck:
        test:
          [
            'CMD',
            'wget',
            '--no-verbose',
            '--tries=1',
            '--spider',
            'http://localhost:9002/api/health',
          ]
        interval: 30s
        timeout: 10s
        retries: 3
        startPeriod: 40s
